# Generated by Django 5.1.5 on 2025-04-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('complex', 'unit_number')},
        ),
        migrations.AddField(
            model_name='apartment',
            name='building_number',
            field=models.PositiveIntegerField(default=9000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('complex', 'building_number'), ('complex', 'unit_number')},
        ),
    ]
