# Generated by Django 5.1.5 on 2025-03-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='num_bathrooms',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
