# Generated by Django 5.1.5 on 2025-04-17 13:31

from django.db import migrations
from django.db import models
from django.utils.timezone import now 


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]


operations = [
    migrations.CreateModel(
        name='Payment',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('payment_amount', models.DecimalField(max_digits=8, decimal_places=2)),
            ('payment_date', models.DateField(default=now)),
            ('payment_method', models.CharField(max_length=50, choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer')])),
            ('is_late_payment', models.BooleanField(default=False)),
            ('lease', models.ForeignKey(on_delete=models.CASCADE, related_name='payments', to='api.lease')),
        ],
    ),
]