# Generated by Django 5.2.1 on 2025-06-01 15:13

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('lease_agreement', 'Lease Agreement'), ('other', 'Other')], max_length=20)),
                ('uploaded_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='apartmentcomplex',
            name='address',
        ),
        migrations.AddField(
            model_name='apartmentcomplex',
            name='city',
            field=models.CharField(default='Atlanta', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentcomplex',
            name='state',
            field=models.CharField(default='GA', max_length=2, validators=[api.models.validate_us_state]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentcomplex',
            name='street',
            field=models.CharField(default='Easthern', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentcomplex',
            name='zipcode',
            field=models.CharField(default='30349', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid US ZIP code (e.g. 12345 or 12345-6789).', regex='^\\d{5}(-\\d{4})?$')]),
            preserve_default=False,
        ),
    ]
