# Generated by Django 5.1.5 on 2025-04-12 01:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apartment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building_number',
            field=models.PositiveIntegerField(validators=[api.models.validate_building]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_number',
            field=models.CharField(max_length=10),
        ),
    ]
