# Generated by Django 5.1.5 on 2025-06-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_payroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
