# Generated by Django 5.1.5 on 2025-04-13 01:52

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_payment_amount_apartment_rent_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.PositiveIntegerField(validators=[api.models.validate_building])),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='api.apartmentcomplex')),
            ],
            options={
                'unique_together': {('complex', 'building_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='api.building'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'unit_number')},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='complex',
        ),
    ]
