const prisma = require("../prisma");
const seed = async () => {
  // TODO: Create Users, Places and Vacations

  const createProperties = async () => {
    const property = [
      {
        // propertyCode: 7255,
        name: "Nayekah Churr LLC",
        address: "240715 Fullstack Academy Graduate",
        city: "Atlanta",
        state: "Georgia",
        zipCode: "30349",
        unit: [],
        leases: [],
      },
    ];

    await prisma.property.createMany({ data: property });
  };
  const createUsers = async () => {
    const users = [
      {
        firstName: "Mario",
        lastName: "Correa",
        email: "mariocorrea29@gmail.com",
        role: "ADMIN",
        phone: "555 - 358 - 7672",
      },
    ];
    await prisma.user.createMany({ data: users });
  };

  const createUnits = async () => {
    const unit = [
      {
        unitNumber: 101,
        rent: 1200.0,
        description:
          "Open-plan living, kitchen with a small bar, bathroom, and a balcony",
        available: false,
        buildingNumber: 100,
      },
      {
        unitNumber: 102,
        rent: 1500.0,
        description:
          "Compact one-bedroom with open living and kitchen space. Small balcony. Ideal for efficient use of space.",
        available: false,
        buildingNumber: 100,
      },
      {
        unitNumber: 103,
        rent: 1900.0,
        description:
          " Two bedrooms, two bathrooms. Large open-concept kitchen and living room with a full-sized dining area. Spacious balcony.",
        available: false,
        buildingNumber: 100,
      },
      {
        unitNumber: 104,
        rent: 1900.0,
        description:
          " Two bedrooms, one designed as a bedroom and the other as an office with built-in desk space. One large bathroom. Compact kitchen with an island.",
        available: false,
        buildingNumber: 100,
      },
      {
        unitNumber: 105,
        rent: 2400.0,
        description:
          "  Three small bedrooms with one shared bathroom, open living area with a minimalist kitchen, designed for efficiency. Small balcony.",
        available: false,
        buildingNumber: 100,
      },
      {
        unitNumber: 201,
        rent: 2200.0,
        description:
          " Ground-level apartment with a private garden patio, two bedrooms, open kitchen-living concept, and one bathroom",
        available: false,
        buildingNumber: 200,
      },
      {
        unitNumber: 202,
        rent: 1800.0,
        description:
          "Two floors, two bedrooms, and a bathroom on the top floor, open kitchen, dining, and living room on the ground floor. Private outdoor space on both levels",
        available: false,
        buildingNumber: 200,
      },
      {
        unitNumber: 203,
        rent: 2500.0,
        description:
          "High ceilings, bedroom located on a mezzanine level, with an open-plan lower level combining living, kitchen, and dining. Large windows to enhance vertical space",
        available: false,
        buildingNumber: 200,
      },
      {
        unitNumber: 204,
        rent: 2500.0,
        description:
          "High ceilings, bedroom located on a mezzanine level, with an open-plan lower level combining living, kitchen, and dining. Large windows to enhance vertical space",
        available: false,
        buildingNumber: 200,
      },
      {
        unitNumber: 205,
        rent: 2100.0,
        description:
          " Two small bedrooms with one shared bathroom. Open kitchen and living area with a small dining nook. Balcony off the living area.",
        available: false,
        buildingNumber: 200,
      },
      {
        unitNumber: 301,
        rent: 1250.0,
        description:
          "One-bedroom unit designed around maximizing corner views with large windows. Open kitchen with dining bar, a spacious bathroom, and a balcony.",
        available: false,
        buildingNumber: 300,
      },
      {
        unitNumber: 302,
        rent: 2500.0,
        description: "3-bedroom condo with private garden",
        available: false,
        buildingNumber: 300,
      },

      {
        unitNumber: 303,
        rent: 1750.0,
        description:
          " Open-plan living, kitchen with a small bar, bathroom, and a balcony",
        available: false,
        buildingNumber: 300,
      },
      {
        unitNumber: 304,
        rent: 2300.0,
        description:
          " A distinct bedroom with a sliding door separating the living space. Compact kitchen with a breakfast bar and outdoor terrace.",
        available: false,
        buildingNumber: 300,
      },
      {
        unitNumber: 305,
        rent: 2300,
        description:
          "High ceilings, bedroom located on a mezzanine level, with an open-plan lower level combining living, kitchen, and dining. Large windows to enhance vertical space",
        available: false,
        buildingNumber: 300,
      },
    ];
    await prisma.unit.createMany({ data: unit });
  };

  const createTenants = async () => {
    const tenants = [
      {
        firstName: "Alice",
        lastName: "johnson",
        email: "alicejohnson@gmail.com",
        phone: 555 - 2345 - 4532,
        role: "tenant",
      },
      {
        firstName: "Mark",
        lastName: "Lee",
        email: "marklee@gmail.com",
        phone: 5552 - 555 - 9877,
        role: "tenant",
      },
      {
        firstName: "Sarah",
        lastName: "Adams",
        email: "sarahadams@gmail.com",
        phone: 555 - 7654 - 2345,
        role: "tenant",
      },
      {
        firstName: "James",
        lastName: "White",
        email: "jameswhite@gmail.com",
        phone: 555 - 4567 - 4532,
        role: "tenant",
      },
      {
        firstName: "Emily",
        lastName: "Baker",
        email: "emilybaker@gmail.com",
        phone: 555 - 6789 - 2345,
        role: "tenant",
      },
      {
        firstName: "Victor",
        lastName: "Chang",
        email: "victorchang@gmail.com",
        phone: 555 - 9012 - 7765,
        role: "tenant",
      },

      {
        firstName: "Bob",
        lastName: "Smith",
        email: "bobsmith@gmail.com",
        phone: 123 - 4567 - 1891,
        role: "tenant",
      },
      {
        firstName: "Carol",
        lastName: "Davis",
        email: "caroldavis@gmail.com",
        phone: 123 - 456 - 7892,
        role: "tenant",
      },
      {
        firstName: "David",
        lastName: "Wilson",
        email: "davidwilson@gmail.com",
        phone_number: 123 - 456 - 7893,
        role: "tenant",
      },
      {
        firstName: "Eva",
        lastName: "Martinez",
        email: "evamartinez@gmail.com",
        phone: 123 - 456 - 7894,
        role: "tenant",
      },
      {
        firstName: "Frank",
        lastName: "Thompson",
        email: "frankthompson@gmail.com",
        phone: 123 - 456 - 7895,
        role: "tenant",
      },
      {
        FirstName: "Grace ",
        lastName: "Lee",
        email: "gracelee@gmail.com",
        phone: 123 - 456 - 7896,
        role: "tenant",
      },
      {
        id: 8,
        firstName: "Henry",
        lastName: "Clark",
        email: "henryclark@gmail.com",
        phone: 123 - 456 - 7897,
        role: "tenant",
      },
      {
        firstName: "Ivy ",
        lastName: "Turner",
        email: "ivyturner@gmail.com",
        phone: 123 - 456 - 7898,
        role: "tenant",
      },
      {
        firstName: "Jack ",
        lastName: "Wilson",
        email: "jackwilson@gmail.com",
        phone: 123 - 456 - 7899,
        role: "tenant",
      },
    ];
    await prisma.tenant.createMany({ data: tenants });
  };
  const createLeases = async () => {
    const leases = [
      {
        unitNumber: 101,
        unitId: 1,
        tenantId: 1,
        leaseStartDate: "2024 - 01 - 10",
        leaseEndDate: "2025 - 06 - 01",
        monthlyRent: 1200,
        securityDeposit: 1200,
        leaseStatus: Active,
      },
      {
        unitNumber: 102,
        unitId: 2,
        tenantId: 2,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 14",
        monthlyRent: 1500,
        securityDeposit: 1500,
        leaseStatus: Active,
      },
      {
        unitNumber: 103,
        unitId: 3,
        tenantId: 3,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 14",
        monthlyRent: 1900,
        securityDeposit: 1500,
        leaseStatus: Active,
      },
      {
        unitNumber: 104,
        unitId: 4,
        tenantId: 4,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 14",
        monthlyRent: 1900,
        securityDeposit: 1500,
        leaseStatus: Active,
      },
      {
        unitNumber: 105,
        unitId: 5,
        tenantId: 5,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 14",
        monthlyRent: 2400,
        securityDeposit: 1500,
        leaseStatus: Active,
      },
      {
        unitNumber: 201,
        unitId: 6,
        tenantId: 6,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 07 - 31",
        monthlyRent: 2200,
        securityDeposit: 1200,
        leaseStatus: Active,
      },
      {
        unitNumber: 202,
        unitId: 7,
        tenantId: 7,
        leaseStartDate: "2024 - 01 - 18",
        leaseEndDate: "2025 - 07 - 31",
        monthlyRent: 1800,
        securityDeposit: 1800,
        leaseStatus: Active,
      },
      {
        unitNumber: 203,
        unitId: 8,
        tenantId: 8,
        leaseStartDate: "2024 - 01 - 18",
        leaseEndDate: "2025 - 07 - 31",
        monthlyRent: 2500,
        securityDeposit: 1800,
        leaseStatus: Active,
      },
      {
        unitNumber: 204,
        unitId: 9,
        tenantId: 9,
        leaseStartDate: "2024 - 01 - 18",
        leaseEndDate: "2025 - 07 - 31",
        monthlyRent: 2500,
        securityDeposit: 1800,
        leaseStatus: Active,
      },
      {
        unitNumber: 205,
        unitId: 10,
        tenantId: 10,
        leaseStartDate: "2024 - 01 - 18",
        leaseEndDate: "2025 - 07 - 31",
        monthlyRent: 2100,
        securityDeposit: 1800,
        leaseStatus: Active,
      },
      {
        unitNumber: 301,
        tenantId: 11,
        unitId: 11,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 08 - 05",
        monthlyRent: 1250,
        securityDeposit: 1000,
        leaseStatus: Active,
      },
      {
        unitNumber: 302,
        tenantId: 12,
        unitId: 12,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 30",
        monthlyRent: 2500,
        securityDeposit: 1600,
        leaseStatus: Active,
      },
      {
        unitNumber: 303,
        unitId: 13,
        tenantId: 13,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 30",
        monthlyRent: 1750,
        securityDeposit: 1600,
        leaseStatus: Active,
      },
      {
        unitNumber: 304,
        unitId: 14,
        tenantId: 14,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 30",
        monthlyRent: 2300,
        securityDeposit: 1600,
        leaseStatus: Active,
      },
      {
        unitNumber: 305,
        unitId: 15,
        tenantId: 15,
        leaseStartDate: "2024 - 01 - 15",
        leaseEndDate: "2025 - 06 - 30",
        monthlyRent: 2300,
        securityDeposit: 1600,
        leaseStatus: Active,
      },
    ];
    await prisma.lease.createMany({ data: leases });
  };
  const createPayments = async () => {
    const payments = [
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 02 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 02 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 02 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 02 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 02 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 03 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 03 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 03 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 03 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 03 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 04 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 04 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 04 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 04 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 04 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 05 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 05 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 05 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 05 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 05 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 06 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 06 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 06 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 06 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 06 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 07 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 07 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 07 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 07 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 07 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 08 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 08 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 08 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 08 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 08 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 1,
        tenantId: 1,
        amount: 1200,
        paymentDate: "2024 - 09 - 15",
        method: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 2,
        tenantId: 2,
        amount: 1500,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "Bank Transfer",
        status: "Paid",
      },
      {
        leaseId: 3,
        tenantId: 3,
        amount: 1900,
        paymentDate: "2024 - 09 - 10",
        paymentMethod: "	Check",
        status: "	Paid",
      },
      {
        laseId: 4,
        tenantId: 4,
        amount: 1800,
        paymentDate: "2024 - 09 - 19",
        paymentMethod: "Credit Card",
        status: "Paid",
      },
      {
        leaseId: 5,
        tenantId: 5,
        amount: 2400,
        paymentDate: "2024 - 09 - 14",
        paymentMethod: "	Bank Transfer",
        status: "	Paid",
      },
      {
        leaseId: 6,
        tenantId: 6,
        amount: 2200,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 7,
        tenantId: 7,
        amount: 1800,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 8,
        tenantId: 8,
        amount: 2500,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 9,
        tenantId: 9,
        amount: 2500,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 10,
        tenantId: 10,
        amount: 2100,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 11,
        tenantId: 11,
        amount: 2500,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 12,
        tenantId: 12,
        amount: 2500,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 13,
        tenantId: 13,
        amount: 1750,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 14,
        tenantId: 14,
        amount: 2300,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
      {
        leaseId: 15,
        tenantId: 15,
        amount: 2300,
        paymentDate: "2024 - 09 - 15",
        paymentMethod: "	Credit Card",
        status: "Paid",
      },
    ];
    await prisma.payment.createMany({ data: payments });
  };
  const createMaintenanceRequests = async () => {
    const MaintenanceRequest = [];
    await prisma.MaintenanceRequest.createMany({ data: MaintenanceRequest });
  };
  await createUsers();
  await createUnits();
  await createProperties();
  await createTenants();
  await createLeases();
  await createPayments();
  await createMaintenanceRequests();
};
seed()
  .then(async () => await prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
