const property = {
  name: "Nayekah Churr LLC",
  address: "240715 Fullstack Academy Graduate",
  city: "Atlanta",
  state: "Georgia",
  zipCode: "30349",

  units: [
    {
      id: 1,
      firstName: "Alice",
      lastName: "johnson",
      email: "alicejohnson@gmail.com",
      phone: "555 - 345 - 4532",
      role: "TENANT",
      unitNumber: 101,
      rent: 1200.0,
      description:
        "Open-plan living, kitchen with a small bar, bathroom, and a balcony",
      available: false,
      buildingNumber: 100,
      leaseStartDate: new Date("2024-01-15"),
      leaseEndDate: new Date("2025-01-15"),
      monthlyRent: 1200,
      securityDeposit: 1200,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 1200,
          paymentDate: new Date("2024 - 02 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1200,
          paymentDate: new Date("2024 - 03 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1200,
          paymentDate: new Date("2024 - 04 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1200,
          paymentDate: new Date("2024 - 05 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1200,
          paymentDate: new Date("2024 - 06 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1200,
          paymentDate: new Date("2024 - 07 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1200,
          paymentDate: new Date("2024 - 08 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1200,
          paymentDate: new Date("2024 - 09 - 15"),
          method: "Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 2,
      firstName: "Mark",
      lastName: "Lee",
      email: "marklee@gmail.com",
      phone: "5552 - 555 - 9877",
      role: "TENANT",
      unitNumber: 102,
      rent: 1500.0,
      description:
        "Compact one-bedroom with open living and kitchen space. Small balcony. Ideal for efficient use of space.",
      available: false,
      buildingNumber: 100,
      leaseStartDate: new Date("2024-01-15"),
      leaseEndDate: new Date("2025-01-15"),
      monthlyRent: 1500,
      securityDeposit: 1500,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 1500,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 1500,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 1500,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 1500,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 1500,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 1500,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 1500,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 1500,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "Bank Transfer",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 3,
      firstName: "Sarah",
      lastName: "Adams",
      email: "sarahadams@gmail.com",
      phone: "555 - 765 - 2345",
      role: "TENANT",
      unitNumber: 103,
      rent: 1900.0,
      description:
        " Two bedrooms, two bathrooms. Large open-concept kitchen and living room with a full-sized dining area. Spacious balcony.",
      available: false,
      buildingNumber: 100,
      leaseStartDate: new Date("2024 - 01 - 10"),
      leaseEndDate: new Date("2025 - 01 -10"),
      monthlyRent: 1900,
      securityDeposit: 1500,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 1900,
          paymentDate: new Date("2024 - 02 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAID",
        },
        {
          amount: 1900,
          paymentDate: new Date("2024 - 03 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAID",
        },
        {
          amount: 1900,
          paymentDate: new Date("2024 - 04 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAIDd",
        },
        {
          amount: 1900,
          paymentDate: new Date("2024 - 05 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAID",
        },
        {
          amount: 1900,
          paymentDate: new Date("2024 - 06 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAID",
        },
        {
          amount: 1900,
          paymentDate: new Date("2024 - 07 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAIDd",
        },
        {
          amount: 1900,
          paymentDate: new Date("2024 - 08 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAIDd",
        },
        {
          amount: 1900,
          paymentDate: new Date("2024 - 09 - 10"),
          paymentMethod: "	Check",
          paymentStatus: "PAIDd",
        },
      ],
    },
    {
      id: 4,
      firstName: "James",
      lastName: "White",
      email: "jameswhite@gmail.com",
      phone: "555 - 456 - 4532",
      role: "TENANT",
      unitNumber: 104,
      rent: 1800.0,
      description:
        " Two bedrooms, one designed as a bedroom and the other as an office with built-in desk space. One large bathroom. Compact kitchen with an island.",
      available: false,
      buildingNumber: 100,
      leaseStartDate: new Date("2024 - 01 - 19"),
      leaseEndDate: new Date("2025 - 01 -19"),
      monthlyRent: 1900,
      securityDeposit: 1500,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 1800,
          paymentDate: new Date("2024 - 02 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 03 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 04 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 05 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 06 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 07 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 08 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 09 - 19"),
          paymentMethod: "Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 5,
      firstName: "Emily",
      lastName: "Baker",
      email: "emilybaker@gmail.com",
      phone: "555 - 789 - 2345",
      role: "TENANT",
      unitNumber: 105,
      rent: 2400.0,
      description:
        "  Three small bedrooms with one shared bathroom, open living area with a minimalist kitchen, designed for efficiency. Small balcony.",
      available: false,
      buildingNumber: 100,
      leaseStartDate: new Date("2024 - 01 - 14"),
      leaseEndDate: new Date("2025 - 01 -14"),
      monthlyRent: 2400,
      securityDeposit: 1500.0,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2400,
          paymentDate: new Date("2024 - 02 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 2400,
          paymentDate: new Date("2024 - 03 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 2400,
          paymentDate: new Date("2024 - 04 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 2400,
          paymentDate: new Date("2024 - 05 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 2400,
          paymentDate: new Date("2024 - 06 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 2400,
          paymentDate: new Date("2024 - 07 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 2400,
          paymentDate: new Date("2024 - 08 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAID",
        },
        {
          amount: 2400,
          paymentDate: new Date("2024 - 09 - 14"),
          paymentMethod: "	Bank Transfer",
          paymentStatus: "PAIDd",
        },
      ],
    },
    {
      id: 6,
      firstName: "Victor",
      lastName: "Chang",
      email: "victorchang@gmail.com",
      phone: "555 - 012 - 7765",
      role: "TENANT",
      unitNumber: 201,
      rent: 2200.0,
      description:
        " Ground-level apartment with a private garden patio, two bedrooms, open kitchen-living concept, and one bathroom",
      available: false,
      buildingNumber: 200,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 2200,
      securityDeposit: 1200,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2200,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2200,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2200,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2200,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2200,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2200,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2200,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2200,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 7,
      firstName: "Bob",
      lastName: "Smith",
      email: "bobsmith@gmail.com",
      phone: "123 - 567 - 1891",
      role: "TENANT",
      unitNumber: 202,
      rent: 1800.0,
      description:
        "Two floors, two bedrooms, and a bathroom on the top floor, open kitchen, dining, and living room on the ground floor. Private outdoor space on both levels",
      available: false,
      buildingNumber: 200,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 1800,
      securityDeposit: 1800,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 1800.0,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800.0,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1800,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 8,
      firstName: "Carol",
      lastName: "Davis",
      email: "caroldavis@gmail.com",
      phone: "123 - 456 - 7892",
      role: "TENANT",
      unitNumber: 203,
      rent: 2500.0,
      description:
        "High ceilings, bedroom located on a mezzanine level, with an open-plan lower level combining living, kitchen, and dining. Large windows to enhance vertical space",
      available: false,
      buildingNumber: 200,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 2500,
      securityDeposit: 1800,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2500,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 9,
      firstName: "David",
      lastName: "Wilson",
      email: "davidwilson@gmail.com",
      phone: "123 - 456 - 7893",
      role: "TENANT",
      unitNumber: 204,
      rent: 2500.0,
      description:
        "High ceilings, bedroom located on a mezzanine level, with an open-plan lower level combining living, kitchen, and dining. Large windows to enhance vertical space",
      available: false,
      buildingNumber: 200,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 2500,
      securityDeposit: 1800,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2500,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 10,
      firstName: "Eva",
      lastName: "Martinez",
      email: "evamartinez@gmail.com",
      phone: "123 - 456 - 7894",
      role: "TENANT",
      unitNumber: 205,
      rent: 2100.0,
      description:
        " Two small bedrooms with one shared bathroom. Open kitchen and living area with a small dining nook. Balcony off the living area.",
      available: false,
      buildingNumber: 200,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 2100,
      securityDeposit: 1800,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2100,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2100,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2100,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2100,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2100,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2100,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2100,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 11,
      firstName: "Frank",
      lastName: "Thompson",
      email: "frankthompson@gmail.com",
      phone: "123 - 456 - 7895",
      role: "TENANT",
      unitNumber: 301,
      rent: 1250.0,
      description:
        "One-bedroom unit designed around maximizing corner views with large windows. Open kitchen with dining bar, a spacious bathroom, and a balcony.",
      available: false,
      buildingNumber: 300,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 1250,
      securityDeposit: 1000,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2500,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 03 - 15"),
          // paymentDate: "2024 - 03 - 15",
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 12,
      firstName: "Grace ",
      lastName: "Lee",
      email: "gracelee@gmail.com",
      phone: "123 - 456 - 7896",
      role: "TENANT",
      unitNumber: 302,
      rent: 2500.0,
      description: "3-bedroom condo with private garden",
      available: false,
      buildingNumber: 300,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 2500,
      securityDeposit: 1600,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2500,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 03 - 15"),
          // paymentDate: "2024 - 03 - 15",
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2500,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 13,
      firstName: "Henry",
      lastName: "Clark",
      email: "henryclark@gmail.com",
      phone: "123 - 456 - 7897",
      role: "TENANT",
      unitNumber: 303,
      rent: 1750.0,
      description:
        " Open-plan living, kitchen with a small bar, bathroom, and a balcony",
      available: false,
      buildingNumber: 300,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 1750,
      securityDeposit: 1600,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 1750,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1750,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1750,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1750,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1750,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1750,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1750,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 1750,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 14,
      firstName: "Ivy ",
      lastName: "Turner",
      email: "ivyturner@gmail.com",
      phone: "123 - 456 - 7898",
      role: "TENANT",
      unitNumber: 304,
      rent: 2300.0,
      description:
        " A distinct bedroom with a sliding door separating the living space. Compact kitchen with a breakfast bar and outdoor terrace.",
      available: false,
      buildingNumber: 300,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 2300,
      securityDeposit: 1600,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2300,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
    {
      id: 15,
      firstName: "Jack ",
      lastName: "Wilson",
      email: "jackwilson@gmail.com",
      phone: "123 - 456 - 7899",
      role: "TENANT",
      unitNumber: 305,
      rent: 2300,
      description:
        "High ceilings, bedroom located on a mezzanine level, with an open-plan lower level combining living, kitchen, and dining. Large windows to enhance vertical space",
      available: false,
      buildingNumber: 300,
      leaseStartDate: new Date("2024 - 01 - 15"),
      leaseEndDate: new Date("2025 - 01 -15"),
      monthlyRent: 2300,
      securityDeposit: 1600,
      leaseStatus: "ACTIVE",
      payments: [
        {
          amount: 2300,
          paymentDate: new Date("2024 - 02 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 03 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 04 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 05 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 06 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 07 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 08 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
        {
          amount: 2300,
          paymentDate: new Date("2024 - 09 - 15"),
          paymentMethod: "	Credit Card",
          paymentStatus: "PAID",
        },
      ],
    },
  ],
};
export default property;
//////////
extra = [
  {
    id: 16,
    buildingNumber: 100,
    rent: 1200,
    available: true,
    description:
      "Cozy 1-bedroom with modern finishes, hardwood floors, and a spacious kitchen.",
  },
  {
    id: 17,
    buildingNumber: 200,
    rent: 1500.0,
    available: true,
    description:
      "Bright 2-bedroom with large windows, open floor plan, and ample closet space.",
  },
  {
    id: 18,
    buildingNumber: 300,
    rent: 1200.0,
    available: true,
    description:
      "Ground-floor unit with patio access, perfect for small pets and outdoor seating.",
  },
  {
    id: 19,
    buildingNumber: 100,
    rent: 1800.0,
    available: true,
    description:
      "Spacious 2-bedroom with a balcony, modern appliances, and in-unit washer/dryer.",
  },
  {
    id: 20,
    buildingNumber: 200,
    rent: 2200.0,
    available: true,
    description:
      "	Large 3-bedroom with a private entrance, ideal for families or shared living.",
  },
  {
    id: 21,
    buildingNumber: 300,
    rent: 1150.0,
    available: true,
    description:
      "Compact 1-bedroom with energy-efficient appliances and a newly renovated bathroom.",
  },
];
